name: Ruby

on:
  pull_request:
  push:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  spec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ["3.2", "3.3", "3.4", "4.0"]

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: RSpec
        run: bundle exec rake spec
